# products.py  –  15 realistic glass & allied products for AmalGus marketplace

PRODUCTS = [
    {
        "id": "P001",
        "name": "Clear Tempered Safety Glass 6mm",
        "category": "Tempered Glass",
        "supplier": "Gujarat Float Glass Ltd.",
        "price_inr": 750,
        "price_unit": "sqm",
        "description": "6mm fully tempered safety glass ideal for office partitions, shower enclosures, and interior glazing. Thermally treated for 5× strength over annealed glass. Polished edges standard.",
        "key_specs": ["6mm thickness", "Clear / Colorless", "Polished edges", "EN 12150 certified", "Max size 3600×2000mm", "Heat-strengthened"],
        "thickness_mm": 6,
        "tags": "tempered safety glass office partition shower clear polished edge certified strength"
    },
    {
        "id": "P002",
        "name": "Laminated Safety Glass 8.76mm (4+4 PVB)",
        "category": "Laminated Glass",
        "supplier": "SafeGlass India Pvt. Ltd.",
        "price_inr": 1350,
        "price_unit": "sqm",
        "description": "8.76mm laminated glass with 0.76mm PVB interlayer. Perfect for balcony railings, staircase balustrades, skylights, and high-wind facades. Holds together on breakage. UV-blocking interlayer.",
        "key_specs": ["8.76mm (4+4 PVB)", "UV protection", "High-wind rated", "IS 2553 Part 2", "Balcony / railing", "Safety on breakage"],
        "thickness_mm": 8.76,
        "tags": "laminated safety glass balcony railing staircase skylight UV protection wind high strength pvb interlayer"
    },
    {
        "id": "P003",
        "name": "Insulated Glass Unit 5+12+5 (Clear)",
        "category": "Insulated Glass",
        "supplier": "EnergyPane Systems",
        "price_inr": 2200,
        "price_unit": "sqm",
        "description": "Double-glazed insulated unit with 5mm float glass, 12mm air spacer, and 5mm float glass. Excellent thermal insulation for energy-efficient commercial and residential windows. U-value ≤ 2.8 W/m²K.",
        "key_specs": ["5+12+5 configuration", "U-value ≤ 2.8", "Argon optional", "Aluminium spacer", "Energy efficient", "2m height compatible"],
        "thickness_mm": 22,
        "tags": "insulated glass unit IGU double glazing energy efficient thermal windows commercial residential 5+12+5 U-value"
    },
    {
        "id": "P004",
        "name": "Float Glass 4mm Clear (Standard)",
        "category": "Float Glass",
        "supplier": "Hindustan National Glass",
        "price_inr": 280,
        "price_unit": "sqm",
        "description": "Standard 4mm clear float glass for residential windows, picture frames, and interior partitions. Budget-friendly option available in bulk. Smooth fire-polished surfaces. IS 2835 compliant.",
        "key_specs": ["4mm thickness", "Clear / Float", "IS 2835", "Budget-friendly", "Bulk available", "Residential use"],
        "thickness_mm": 4,
        "tags": "float glass 4mm clear cheap budget residential windows bulk quantity standard affordable"
    },
    {
        "id": "P005",
        "name": "Bronze Tinted Heat-Reflective Glass 6mm",
        "category": "Tinted / Reflective Glass",
        "supplier": "SunShield Glazing Co.",
        "price_inr": 920,
        "price_unit": "sqm",
        "description": "6mm bronze tinted glass with pyrolytic heat-reflective coating. Reduces solar heat gain by 40%. Ideal for facades, curtain walls, and commercial building exteriors. Aesthetic warmth with functional performance.",
        "key_specs": ["6mm thickness", "Bronze tint", "Heat reflective", "Solar factor 0.45", "Facade / curtain wall", "SHGC 0.45"],
        "thickness_mm": 6,
        "tags": "bronze tinted reflective heat solar facade curtain wall commercial cladding building exterior warm tone"
    },
    {
        "id": "P006",
        "name": "Tempered Glass Shower Enclosure 8mm",
        "category": "Tempered Glass",
        "supplier": "AquaGlass India",
        "price_inr": 1100,
        "price_unit": "sqm",
        "description": "8mm fully tempered glass with EasyClean hydrophobic coating for shower enclosures and wet areas. Frameless design compatible. Polished edges and drilled holes on request.",
        "key_specs": ["8mm thickness", "EasyClean coating", "Hydrophobic", "Frameless compatible", "Drilled holes", "Wet area rated"],
        "thickness_mm": 8,
        "tags": "tempered glass shower bathroom wet area 8mm frameless hydrophobic easy clean drilled"
    },
    {
        "id": "P007",
        "name": "Laminated Glass 10.38mm (5+5 PVB) UV Guard",
        "category": "Laminated Glass",
        "supplier": "SafeGlass India Pvt. Ltd.",
        "price_inr": 1850,
        "price_unit": "sqm",
        "description": "10.38mm laminated safety glass with advanced UV-blocking PVB interlayer. Blocks 99% UV radiation. Suitable for museum displays, high-end retail, skylights, and wind-load facade glazing.",
        "key_specs": ["10.38mm (5+5 PVB)", "99% UV block", "High wind load", "Museum quality", "IS 2553 certified", "Safety interlayer"],
        "thickness_mm": 10.38,
        "tags": "laminated UV protection 10mm balcony skylight high wind museum retail safety thick strong"
    },
    {
        "id": "P008",
        "name": "Low-E Insulated Glass Unit 6+12+6",
        "category": "Insulated Glass",
        "supplier": "EnergyPane Systems",
        "price_inr": 3100,
        "price_unit": "sqm",
        "description": "High-performance double-glazed unit with Low-E coating on surface #2. 6mm + 12mm air gap + 6mm configuration. U-value ≤ 1.8 W/m²K with argon fill. Best-in-class energy savings for LEED projects.",
        "key_specs": ["6+12+6 Low-E", "U-value ≤ 1.8", "Argon filled", "LEED compatible", "SHGC 0.28", "Energy saving"],
        "thickness_mm": 24,
        "tags": "insulated glass low-e IGU energy efficient LEED argon double glazed 6+12+6 thermal performance green building"
    },
    {
        "id": "P009",
        "name": "Mirror Glass 5mm (Copper-Free Silver)",
        "category": "Mirror",
        "supplier": "Reflecto Glass Works",
        "price_inr": 480,
        "price_unit": "sqm",
        "description": "5mm silver mirror with copper-free backing for superior corrosion resistance. Ideal for bathrooms, dressing rooms, gyms, and retail interiors. High reflectivity, edge-polished finish available.",
        "key_specs": ["5mm float base", "Copper-free silver", "High reflectivity", "Moisture resistant", "Polished edge option", "Interior use"],
        "thickness_mm": 5,
        "tags": "mirror glass silver copper free bathroom gym retail dressing room reflective 5mm interior polished"
    },
    {
        "id": "P010",
        "name": "Frosted / Obscure Glass 4mm",
        "category": "Decorative Glass",
        "supplier": "Decor Glass Studio",
        "price_inr": 420,
        "price_unit": "sqm",
        "description": "4mm acid-etched frosted glass for privacy partitions, bathroom windows, and decorative panels. Uniform diffuse appearance, easy to clean. Available in custom patterns.",
        "key_specs": ["4mm thickness", "Acid-etched", "Privacy / frosted", "Custom patterns", "Uniform diffusion", "Interior partitions"],
        "thickness_mm": 4,
        "tags": "frosted obscure privacy acid etched decorative bathroom partition office 4mm diffuse pattern"
    },
    {
        "id": "P011",
        "name": "Aluminium Spider Fitting Hardware Set",
        "category": "Hardware / Fittings",
        "supplier": "MetalCraft Glazing Hardware",
        "price_inr": 3500,
        "price_unit": "set",
        "description": "Stainless steel / anodised aluminium 4-arm spider fitting for structural glass facades and frameless glass walls. Each set covers 1 junction point. Compatible with 10–19mm tempered glass.",
        "key_specs": ["4-arm spider", "SS 316 / Anodised Al", "Structural glazing", "10–19mm glass", "Load rated 200kg", "Corrosion resistant"],
        "thickness_mm": None,
        "tags": "hardware spider fitting structural glass facade frameless stainless steel aluminium fittings point fixed"
    },
    {
        "id": "P012",
        "name": "UPVC Window Profile with Double Glaze",
        "category": "Window Systems",
        "supplier": "FensterIndia Pvt. Ltd.",
        "price_inr": 4800,
        "price_unit": "sqm",
        "description": "UPVC casement window system pre-fitted with 5+12+5 IGU. Sound insulation 32 dB. Thermal break design. Suitable for residential and commercial projects. White / wood grain finish.",
        "key_specs": ["UPVC frame", "5+12+5 IGU", "32 dB sound", "Thermal break", "White / wood grain", "Residential / commercial"],
        "thickness_mm": 22,
        "tags": "UPVC window system double glazed insulated residential sound insulation thermal break casement"
    },
    {
        "id": "P013",
        "name": "Wired / Georgian Safety Glass 6.5mm",
        "category": "Safety Glass",
        "supplier": "Heritage Glass Mills",
        "price_inr": 680,
        "price_unit": "sqm",
        "description": "6.5mm wired glass with embedded square-pattern steel wire mesh. Fire-resistant for 30 minutes (E30 rated). Used in fire-rated doors, skylights, and industrial applications. Polished finish available.",
        "key_specs": ["6.5mm wired", "E30 fire rated", "Steel mesh", "Fire doors", "Industrial use", "Skylights"],
        "thickness_mm": 6.5,
        "tags": "wired safety fire rated georgian glass fire door industrial skylight E30 steel mesh thick"
    },
    {
        "id": "P014",
        "name": "Structural Silicone Sealant (600ml)",
        "category": "Sealants & Accessories",
        "supplier": "GlazeSeal Solutions",
        "price_inr": 480,
        "price_unit": "cartridge",
        "description": "Neutral-cure, UV-stable structural silicone sealant for glazing, aluminium curtain walls, and facade joints. Shore A hardness 35. Movement accommodation ±25%. ASTM C920 certified.",
        "key_specs": ["Neutral cure", "UV stable", "ASTM C920", "±25% movement", "Shore A 35", "Curtain wall / facade"],
        "thickness_mm": None,
        "tags": "silicone sealant structural glazing curtain wall facade UV stable neutral cure accessories"
    },
    {
        "id": "P015",
        "name": "Toughened Glass Staircase Balustrade 12mm",
        "category": "Tempered Glass",
        "supplier": "StairSafe Glass India",
        "price_inr": 1950,
        "price_unit": "sqm",
        "description": "12mm fully toughened (tempered) glass panels for staircase balustrades and frameless railings. Heavy-duty, drilled holes pre-made for clamp fittings. Polished edges and CNC cutouts available.",
        "key_specs": ["12mm tempered", "Staircase balustrade", "Pre-drilled", "CNC cutouts", "Polished edges", "Heavy-duty"],
        "thickness_mm": 12,
        "tags": "tempered toughened thick 12mm staircase balustrade railing frameless drilled polished heavy duty structural"
    },
]